{% set data = load_setup_py_data() %}

package:
  name: ndx-franklab-novela
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/NovelaNeuro/ndx-franklab-novela

build:
  number: 0

requirements:
  build:
    - python=3.7.4
    - setuptools
    - hdmf==1.6.1
    - python-dateutil==2.8.0=py_0
    - pynwb==1.3.0
  run:
    - python=3.7.4
    - python-dateutil=2.8.0=py_0
    - hdmf==1.6.1
    - pynwb==1.3.0
    - pytest

