{% set data = load_setup_py_data() %}

package:
  name: ndx-franklab-novela
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/NovelaNeuro/ndx-franklab-novela

build:
  number: 0

requirements:
  build:
    - python==3.8
    - setuptools
    - hdmf==3.1.1
    - python-dateutil
    - pynwb==2.1.1
  run:
    - python>=3.6
    - python-dateutil
    - hdmf==3.1.1,<4
    - pynwb==2.0.0,<4
    - pytest
